### ISSUE TITLE
Page bottom not visible

### ISSUE THREAD

**Issue by seriouz** [Phu1237/vscode-vs-browser#1]
Thanks for you cool extensions! But I cannot scroll fully to the bottom, so some percentage of the page's bottom are hidden:
![grafik](https://user-images.githubusercontent.com/4722613/150513950-273c0e21-4fd7-405d-bcd7-70f6e30926f9.png)

**Comment by Phu1237** [comment]
I have fixed your issue in v1.0.5. Please update your extension and check again.
Feel free to ask me if you need any help! Thank you for using my extension. ╰(*°▽°*)╯
