### ISSUE TITLE
Is it possible to add the option to simulate mobile devices like Chrome?

### ISSUE THREAD

**Issue by bladetin** [Phu1237/vscode-vs-browser#11]
Your plugin is written great, it fits my needs very well, but it can't resize its view to mobile devices, I hope you will consider adding this feature if you can, thank you very much for providing us with such a good plugin.

**Comment by bladetin** [comment]
like this
![image](https://user-images.githubusercontent.com/92976987/201520589-be074f05-da91-4011-a197-ac7d242219b4.png)

**Comment by Phu1237** [comment]
It is not possible at this time due to the limit of Visual Studio Code
