### ISSUE TITLE
Show related site source in dev-tools

### ISSUE THREAD

**Issue by givik** [Phu1237/vscode-vs-browser#14]
When I click the **Inspect** button I see the entire Vscode editor source code in dev-tools.

Can I have a more natural web development experience and associate source code only with the opened file? 

Thanks

I love VS Browser! <3

**Comment by Phu1237** [comment]
@givik 
Hi! Thank you for using my extension.
Can you try this and let me know if it fits your needs?
![image](https://user-images.githubusercontent.com/9032235/231034965-3a01e95a-4b52-4f53-a0cd-7a7caeffd46b.png)
![image](https://user-images.githubusercontent.com/9032235/231035068-ce978f67-7855-4cea-a2d0-cc7307fef6ac.png)
Thanks!

**Comment by givik** [comment]
Thanks. There is no such possibility. This option is disabled for me.

**Comment by Phu1237** [comment]
@givik 
Can you give me your screenshots so I can help you in the right way?
Thank you!
