### ISSUE TITLE
Add ability to view from VS sidebar

### ISSUE THREAD

**Issue by sguergachi** [Phu1237/vscode-vs-browser#15]
VS Code has a sidebar feature that this should be built into, so you dont have to launch the browser via command pallet.

![image](https://user-images.githubusercontent.com/615386/235144417-848bdcc7-4308-428f-bc45-14bbbf02e0cf.png)

As an example, GitLens integrates with the sidebar.

**Comment by Phu1237** [comment]
I will try it. Thanks for your suggestion 😊

**Comment by Phu1237** [comment]
@sguergachi 
I have added this feature in version 2.2.0
Please help me to check it and give me any feedback if you have it
Thank you for using my extension and suggesting a good idea to improve my extension! 🎉
