### ISSUE TITLE
Open dev console only in the VS Browser tab

### ISSUE THREAD

**Issue by iamismile** [Phu1237/vscode-vs-browser#18]
Dev console open for whole VS Code.

![Screenshot from 2023-08-25 23-54-20](https://github.com/Phu1237/vscode-vs-browser/assets/48013463/72750e31-e4d1-4e7d-adef-da5b7dde265d)

It would be great if it only opened for the VS Browser tab, not for the whole VS code app.

Thanks for your extension. ❤️

**Comment by Phu1237** [comment]
@iamismile 
Hi! Thank you for using my extension 🎉
You can choose the option for the iframe console only to debug online for your website here (at red square sharp)
![image](https://github.com/Phu1237/vscode-vs-browser/assets/9032235/3d5f2997-834f-49a1-a9a7-f4fb7868d669)

**Comment by iamismile** [comment]
@Phu1237 
Thanks for your reply.
In the browser dev console remains open only for the tab that I opened. I want that kind of behavior.

**Comment by Phu1237** [comment]
@iamismile 
Sorry for the missed response
As I researched, the VS Code does not support this so I think you have to do it manual until it available so I can implement it into the extension
Thank you for using my extension! 🎉
