### ISSUE TITLE
Can't access external sites

### ISSUE THREAD

**Issue by lucasvazq** [Phu1237/vscode-vs-browser#2]
For example, if you try to access https://google.com, you'll notice that the page never loads.
And, if you open the console, it displays the following error:
```
[Extension Host] Blocked a frame with origin "vscode-webview://***" from accessing a cross-origin frame.
```

**Comment by Phu1237** [comment]
![image](https://user-images.githubusercontent.com/9032235/159491334-0ac40e3f-3610-4410-b98d-835a13f5233d.png)
Please turn on this setting so that you can access the external site. But that will lead to can't access local sites (ex: localhost)

**Comment by lucasvazq** [comment]
Oh, that's a bad tradeoff. I want to open my localhost and also my slack :rofl:
