### ISSUE TITLE
Feature: file pseudo protocol

### ISSUE THREAD

**Issue by mynery** [Phu1237/vscode-vs-browser#22]
I am managing a markdown project and want to just preview the generated html and tinker around a bit with inspections and the whole stuff the extension actually provides.
However, since this site will be static, I don't use a local webserver but rather checking it in my browser via file:// urls.
Sadly, this just doesn't seem to work at all in thie extension.
Any chance to get that feature? I wouldn't even need a file listing, I would be perfectly happy with just watching files I can specify the path for (and therefore have working links between the pages).

Besides the obvious optional feature of directory listings, another really good quality of live feature would the option to just open any htm(l) file in the project that way.

**Comment by Phu1237** [comment]
I will close this issue because I have no plan on implementing a function like `Live server` yet
I may implement it in the future
Thank you for using my extension! 🎉
