### ISSUE TITLE
VS Browser shows blank page after the vscode new update

### ISSUE THREAD

**Issue by samislam** [Phu1237/vscode-vs-browser#24]
![image](https://github.com/Phu1237/vscode-vs-browser/assets/59496975/5348987d-00b8-4162-84be-6b305fb0473b)

After VSCode [1.86](https://code.visualstudio.com/updates) I got this problem, every site can't be visited and it always shows white page.

**Comment by Stefan2142** [comment]
Im getting the same issue

**Comment by Phu1237** [comment]
![image](https://github.com/Phu1237/vscode-vs-browser/assets/9032235/1d716a7b-6e90-4749-977f-50eead309451)
Sorry for the long response @Stefan2142 @samislam 
Can you help me confirm is the extension still working or not?
I have tried it with google and it still work
Thank you!

**Comment by Heather77malinmama** [comment]
![image](https://github.com/Phu1237/vscode-vs-browser/assets/101106513/e3e364b7-58f9-42df-a8b1-60074b39e9fd)
After turning on proxy mode, tho it displays google search page in Arabic, it can't do anything.

**Comment by Phu1237** [comment]
@Heather77malinmama 
It's the limit of the current proxy mode
I'm working on local proxy that let you do those things but because I have zero experience in Nodejs proxy server so it may take time for a completely working proxy
Thank you for using my extension!
