### ISSUE TITLE
After The VS Code updated to 1.90.0, the local resource can't be resolved

### ISSUE THREAD

**Issue by libukai** [Phu1237/vscode-vs-browser#26]
After The VS Code updated to 1.90.0, the local resource can't be resolved.

![CleanShot 2024-06-07 at 16 01 02@2x](https://github.com/Phu1237/vscode-vs-browser/assets/5654585/d0421d72-7c7a-4581-a7ce-266cd53bc695)

At the meantime, the url in the edge browser works fine.

![CleanShot 2024-06-07 at 16 00 45@2x](https://github.com/Phu1237/vscode-vs-browser/assets/5654585/6725756b-8719-4b65-b717-6e7d77b8eb58)

The extension is very helpful for me, I'll appreciate it if you can update it.

Thanks.

**Comment by Phu1237** [comment]
@libukai 
Hi! Thank you for your report.
Are you using proxy mode?

**Comment by libukai** [comment]
Thank you very much for the recent update, I can finally use it again.

**Comment by Phu1237** [comment]
Feel free to ask me if you need any help! Thank you for using my extension. ╰(°▽°)╯
