### ISSUE TITLE
can't access external site

### ISSUE THREAD

**Issue by djacks6278** [Phu1237/vscode-vs-browser#3]
#2 duplicate
when external site set 'x-frame-option'
vs browser can't access... why this browser show all site in iframe?
my proxy setting is enabled

**Comment by Phu1237** [comment]
Can you give me the web URL that you can't go to even if the proxy setting is enabled? Because the proxy mode uses an additional server to get the website content (in backend not by iframe)

**Comment by Phu1237** [comment]
And for your question about why this browser shows all sites in an iframe: This is a workaround method because vscode doesn't support open websites directly in webview (just can use normal HTML js)

**Comment by djacks6278** [comment]
I can't give url cuz is private server
And i checked local server wamp setup
On windows 11 and latest nginx php8.1 mariadb
Set option x-frame-option is sameorigin
And i try connect to ip address to localserver
And i got a same issue in vsbrowser

I think about some chrime app
Ignore x frame option
We need check that app for make solve this issue

**Comment by Phu1237** [comment]
Understood! This is how the proxy mode work: The proxy mode uses an additional server to get the website content so the website must be public on the internet so the proxy server can reach it.
- So in your case, if your server is private the proxy mode won't help you.
=> Did you try to whitelist the IP so if it matches, the `X-Frame-Options: sameorigin` won't add to the header

**Comment by Phu1237** [comment]
In your case, I'm thinking about adding a setting so that you can customize the proxy URL. With that, you can start a private server yourself in your server so that you don't need to use a public proxy server anymore which can't access to a private server

**Comment by djacks6278** [comment]
ofc i add my ip to connect my private server
and i try xframeoption add whitelist ip
but my word mean is some case i think many server use x-frame-option
and if this browser can ignore x-frame header or can strip header
this issue is will be fix

and vscode dosen't have extension like this vsbrowser
many live preview extension is just for localserver
so i want this extension can access other site for preview

**Comment by Phu1237** [comment]
I understand what you mean but this browser is just a normal HTML js so if HTML js can do that, this browser can too. I will think about another method that can access a private server without any additional steps in the future.
In conclusion: The proxy mode just can bypass the public websites/servers at the moment. I will find another way to handle this so it can work as a normal browser.
If you have any suggestions, please tell me so that I can make my extension work better. Thanks 🎉

**Comment by Phu1237** [comment]
@djacks6278 in version 2.0.0 I have added a local proxy server but it has many bugs and limits at the moment. I'm working on it to work with all pages like a normal browser. Just want to update my work. Thanks for using my extension.

**Comment by SheepDomination** [comment]
It is mentioned to turn on proxy mode within the setting so one can visit a site outside of the local host; unfortunately that is not working when this option is turned on. I was hoping for a browser within a tab in visual studio code for quite some time but this still seems to not work effectively with many extensions that tried this but failed miserable.

**Comment by Phu1237** [comment]
@SheepDomination 
Please try the newest version.
I have fixed it
You can go to localhost website even if the proxy mode is enabled now
