### ISSUE TITLE
not able to access local html

### ISSUE THREAD

**Issue by rarajabs** [Phu1237/vscode-vs-browser#6]
Hi,

I am trying to view a local HTML file in VS Code, but I saw errors in console.

![image](https://user-images.githubusercontent.com/1460421/182607942-6bfed08d-2981-4db9-a2ba-3442e50ad2a9.png)

**Comment by Phu1237** [comment]
This is the limit of the browser. The local proxy server should resolve this but it isn't stable yet so I recommend you to use an extension like [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) to deploy your HTML to a domain like http://localhost to use my extension.
Thanks!
