### ISSUE TITLE
Uncaught Errors

### ISSUE THREAD

**Issue by UdaySriHarsha** [Phu1237/vscode-vs-browser#7]
Webview is Disposed x 5

**Comment by Phu1237** [comment]
Hi! Can you give me the guide to representing the errors? Because I try it on my vscode and it is still working.
Thanks!
![image](https://user-images.githubusercontent.com/9032235/183321885-ca9137ad-627d-4f73-9223-8545cfb30b13.png)

**Comment by UdaySriHarsha** [comment]
maybe that was a temporary issue, closing
found new issue will be creating it
