### ISSUE TITLE
Doesn't load even http://localhost at all

### ISSUE THREAD

**Issue by ghost** [Phu1237/vscode-vs-browser#8]
i tried even the local file:/// and the google search engine as well and still it didn't open, the settings file is as is and not modified

![image](https://user-images.githubusercontent.com/104245375/183325444-a8c583b3-f161-43dd-8b18-f742dfaeb43f.png)

Console Logs
https://gist.github.com/UdaySriHarsha/a12fee13934a447b321a06f8b476b4a5

**Comment by Phu1237** [comment]
Thanks! I will try to fix it as soon as possible!

**Comment by praenubilus** [comment]
having the same issue, don't load any addresses

**Comment by praenubilus** [comment]
I have updated to latest version (2.0.9), but for most website it doesn't show anything or response code. Just a blank page

![image](https://user-images.githubusercontent.com/547418/187314371-9f04a6ee-4365-45ad-843e-033cb7d65806.png)

**Comment by Phu1237** [comment]
@praenubilus Please try Proxy mode if you want to access an external page like google, slack, etc. because most of it blocks the outcoming iframe.
Thanks!

**Comment by aronreisx** [comment]
> I have updated to latest version (2.0.9), but for most website it doesn't show anything or response code. Just a blank page
> 
> ![image](https://user-images.githubusercontent.com/547418/187314371-9f04a6ee-4365-45ad-843e-033cb7d65806.png)

I am facing the same problem. I've tried to enable proxy mode and test again, but no success.

**Comment by Oliver-Habersetzer** [comment]
![image](https://user-images.githubusercontent.com/42864929/218352846-a7b07fd9-eaaf-435c-8640-6cedb58b2c3a.png)

well, I seem to have a similar issue. I guess it's rly down to the iframe used.

isn't there any alternative like shipping a minimal docker container with this extension.
It could have a very basic browser installed and some remote desktop software like x11 installed.
Then you'd "only" add x11 support to VSCode editor tabs.

I rly wish this would just work, but everything HAS to be electron nowadays I guess :'D

**Comment by Phu1237** [comment]
@Oliver-Habersetzer 
Did you try to turn on Proxy mode?
![image](https://user-images.githubusercontent.com/9032235/218460574-98659edd-72ad-4362-a063-700b4bb59c48.png)
It can help you in some cases. I'm working on local nodejs proxy but nothing is ready yet to fix this issue
