### ISSUE TITLE
Saving a file casues browser to scroll back to top :(

### ISSUE THREAD

**Issue by iyadahmed** [Phu1237/vscode-vs-browser#9]

**Comment by Phu1237** [comment]
I have addressed your issue! Thank you for the report.
I will try to solve this as fast as possible.
Thank you for using my extension!

**Comment by Phu1237** [comment]
I have fixed it in version 2.0.9. Please update your extension to the latest version to fix this bug.
Thank you for using my extension!

**Comment by iyadahmed** [comment]
Thank you
